apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: demo-service
        image: ghcr.io/dtanwer/deployment-check:beta
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: postgres-host
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "admin"
        - name: DB_DATABASE
          value: "postgres"

---

apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30009


